// Top-level build file.
buildscript {
    ext {
        kotlin_version = '1.8.22'
        agp_version = '7.4.2'
        arcore_version = '1.45.0'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    // repositories are declared in settings.gradle (dependencyResolutionManagement)
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
